package com.hotel.hotel_backend.service;

import com.hotel.hotel_backend.dto.request.CreateRoomUnitRequest;
import com.hotel.hotel_backend.dto.request.UpdateRoomUnitRequest;
import com.hotel.hotel_backend.dto.response.HotelRoomUnitResponse;
import com.hotel.hotel_backend.dto.response.RoomUnitResponse;
import com.hotel.hotel_backend.dto.response.RoomUnitSummaryResponse;
import com.hotel.hotel_backend.entity.Hotel;
import com.hotel.hotel_backend.entity.Room;
import com.hotel.hotel_backend.entity.RoomUnit;
import com.hotel.hotel_backend.entity.RoomUnitStatus;
import com.hotel.hotel_backend.exeption.ApiException;
import com.hotel.hotel_backend.exeption.ErrorCode;
import com.hotel.hotel_backend.repository.HotelRepository;
import com.hotel.hotel_backend.repository.RoomRepository;
import com.hotel.hotel_backend.repository.RoomUnitRepository;
import com.hotel.hotel_backend.service.InventoryService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@RequiredArgsConstructor
@Transactional
public class RoomUnitService {

    private final RoomUnitRepository roomUnitRepository;
    private final RoomRepository roomRepository;
    private final HotelRepository hotelRepository;
    private final SecurityService securityService;
    private final InventoryService inventoryService;

    @Transactional(readOnly = true)
    public List<RoomUnitResponse> getUnits(Long roomId) {
        Room room = findOwnedRoom(roomId);
        return roomUnitRepository.findByRoomIdOrderByFloorAscRoomNumberAsc(room.getId())
                .stream()
                .map(this::mapToResponse)
                .toList();
    }

    public RoomUnitResponse create(Long roomId, CreateRoomUnitRequest request) {
        // FIX BUG-005: Use SELECT ... FOR UPDATE to prevent the TOCTOU race condition.
        // Without the lock, two concurrent requests could both pass the count check and
        // both insert, producing more RoomUnits than Room.quantity allows.
        Room room = findOwnedRoomForUpdate(roomId);

        if (request.roomNumber() != null && !request.roomNumber().isBlank()) {
            String normalized = request.roomNumber().trim();
            Long hotelId = room.getHotel().getId();
            if (roomUnitRepository.countByHotelIdAndRoomNumber(hotelId, normalized, null) > 0) {
                throw new ApiException(ErrorCode.CONFLICT,
                        "Số phòng \"" + normalized + "\" đã tồn tại trong cơ sở này");
            }
        }

        long currentCount = roomUnitRepository.countByRoomId(room.getId());
        if (currentCount >= room.getQuantity()) {
            throw new ApiException(ErrorCode.VALIDATION_ERROR,
                    "Đã đủ " + room.getQuantity() + " phòng theo cấu hình loại phòng. " +
                    "Hãy tăng số lượng trong cài đặt loại phòng trước.");
        }

        RoomUnit unit = new RoomUnit();
        unit.setRoom(room);
        unit.setRoomNumber(request.roomNumber() == null ? null : request.roomNumber().trim());
        unit.setFloor(request.floor());
        unit.setStatus(request.status() != null ? request.status() : RoomUnitStatus.AVAILABLE);
        unit.setNotes(request.notes());
        unit.setGuestName(request.guestName());
        unit.setAutoGenerated(false);

        roomUnitRepository.save(unit);
        return mapToResponse(unit);
    }

    public RoomUnitResponse update(Long roomId, Long unitId, UpdateRoomUnitRequest request) {
        Room room = findOwnedRoom(roomId);
        RoomUnit unit = findUnit(unitId, room.getId());

        if (request.roomNumber() != null && !request.roomNumber().isBlank()) {
            String normalized = request.roomNumber().trim();
            Long hotelId = room.getHotel().getId();
            if (roomUnitRepository.countByHotelIdAndRoomNumber(hotelId, normalized, unit.getId()) > 0) {
                throw new ApiException(ErrorCode.CONFLICT,
                        "Số phòng \"" + normalized + "\" đã tồn tại trong cơ sở này");
            }
            unit.setRoomNumber(normalized);
        } else {
            unit.setRoomNumber(null);
        }

        unit.setFloor(request.floor());
        unit.setStatus(request.status());
        unit.setNotes(request.notes());
        unit.setGuestName(request.guestName());
        unit.setCoverImageUrl(request.coverImageUrl());

        return mapToResponse(unit);
    }

    public void delete(Long roomId, Long unitId) {
        Room room = findOwnedRoom(roomId);
        RoomUnit unit = findUnit(unitId, room.getId());

        if (unit.getStatus() == RoomUnitStatus.OCCUPIED) {
            throw new ApiException(ErrorCode.VALIDATION_ERROR,
                    "Không thể xóa phòng đang có khách. " +
                    "Đảm bảo khách đã trả phòng và trạng thái không còn là OCCUPIED trước khi xóa.");
        }

        roomUnitRepository.delete(unit);

        // Decrement declared quantity to match actual physical count.
        int newQuantity = Math.max(0, room.getQuantity() - 1);
        room.setQuantity(newQuantity);

        // FIX BUG-003: Re-sync DailyInventory after quantity drops.
        // Without this, availableRooms stays at the old higher value, enabling overbooking.
        // generateInventory uses room.getQuantity() which now holds newQuantity (dirty entity,
        // same transaction — JPA will flush the updated value before the inventory queries run).
        inventoryService.generateInventory(room);
    }

    public RoomUnitResponse setCoverImage(Long roomId, Long unitId, String imageUrl) {
        Room room = findOwnedRoom(roomId);
        RoomUnit unit = findUnit(unitId, room.getId());
        unit.setCoverImageUrl(imageUrl);
        return mapToResponse(unit);
    }

    // ── Summary (used by RoomService when mapping RoomResponse) ──────────

    @Transactional(readOnly = true)
    public RoomUnitSummaryResponse getSummary(Long roomId) {
        long total       = roomUnitRepository.countByRoomId(roomId);
        long available   = roomUnitRepository.countByRoomIdAndStatus(roomId, RoomUnitStatus.AVAILABLE);
        long occupied    = roomUnitRepository.countByRoomIdAndStatus(roomId, RoomUnitStatus.OCCUPIED);
        long maintenance = roomUnitRepository.countByRoomIdAndStatus(roomId, RoomUnitStatus.MAINTENANCE);
        long cleaning    = roomUnitRepository.countByRoomIdAndStatus(roomId, RoomUnitStatus.CLEANING);
        return new RoomUnitSummaryResponse(total, available, occupied, maintenance, cleaning);
    }

    @Transactional(readOnly = true)
    public List<HotelRoomUnitResponse> getUnitsByHotel(Long hotelId) {
        Hotel hotel = hotelRepository.findById(hotelId)
                .orElseThrow(() -> new ApiException(ErrorCode.NOT_FOUND, "Không tìm thấy cơ sở lưu trú"));
        Long currentUserId = securityService.getCurrentPrincipal().userId();
        if (!hotel.getOwner().getId().equals(currentUserId)) {
            throw new ApiException(ErrorCode.FORBIDDEN);
        }
        // findByHotelId already filters out INACTIVE rooms via JPQL
        return roomUnitRepository.findByHotelId(hotelId)
                .stream()
                .map(this::mapToHotelResponse)
                .toList();
    }

    // ── Helpers ───────────────────────────────────────────────────────────

    private Room findOwnedRoom(Long roomId) {
        Room room = roomRepository.findById(roomId)
                .orElseThrow(() -> new ApiException(ErrorCode.NOT_FOUND, "Không tìm thấy loại phòng"));
        Long currentUserId = securityService.getCurrentPrincipal().userId();
        if (!room.getHotel().getOwner().getId().equals(currentUserId)) {
            throw new ApiException(ErrorCode.FORBIDDEN);
        }
        return room;
    }

    // FIX BUG-005: Locked variant used only for create() to prevent over-provisioning
    // under concurrent requests. Acquires a row-level write lock on the Room row so
    // the count-then-insert window is serialised at the database level.
    private Room findOwnedRoomForUpdate(Long roomId) {
        Room room = roomRepository.findByIdForUpdate(roomId)
                .orElseThrow(() -> new ApiException(ErrorCode.NOT_FOUND, "Không tìm thấy loại phòng"));
        Long currentUserId = securityService.getCurrentPrincipal().userId();
        if (!room.getHotel().getOwner().getId().equals(currentUserId)) {
            throw new ApiException(ErrorCode.FORBIDDEN);
        }
        return room;
    }

    private RoomUnit findUnit(Long unitId, Long roomId) {
        return roomUnitRepository.findByIdAndRoomId(unitId, roomId)
                .orElseThrow(() -> new ApiException(ErrorCode.NOT_FOUND, "Không tìm thấy phòng cụ thể"));
    }

    private RoomUnitResponse mapToResponse(RoomUnit unit) {
        return new RoomUnitResponse(
                unit.getId(),
                unit.getRoom().getId(),
                unit.getRoomNumber(),
                unit.getFloor(),
                unit.getStatus(),
                unit.getNotes(),
                unit.getGuestName(),
                unit.getCoverImageUrl(),
                unit.isAutoGenerated(),
                unit.getCreatedAt(),
                unit.getUpdatedAt()
        );
    }

    private HotelRoomUnitResponse mapToHotelResponse(RoomUnit unit) {
        Room room = unit.getRoom();
        return new HotelRoomUnitResponse(
                unit.getId(),
                room.getId(),
                room.getName(),
                room.getRoomCategory(),
                room.getCoverImageUrl(),
                unit.getRoomNumber(),
                unit.getFloor(),
                unit.getStatus(),
                unit.getNotes(),
                unit.getGuestName(),
                unit.getCoverImageUrl(),
                unit.isAutoGenerated(),
                unit.getCreatedAt(),
                unit.getUpdatedAt()
        );
    }
}
