package com.hotel.hotel_backend.dto.response;

import com.hotel.hotel_backend.entity.RoomCategory;
import com.hotel.hotel_backend.entity.RoomUnitStatus;

import java.time.OffsetDateTime;

public record HotelRoomUnitResponse(
        Long id,
        Long roomId,
        String roomName,
        RoomCategory roomCategory,
        String roomCoverImageUrl,
        String roomNumber,
        Integer floor,
        RoomUnitStatus status,
        String notes,
        String guestName,
        String coverImageUrl,
        boolean autoGenerated,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt
) {}
