package com.hotel.hotel_backend.dto.response;

import com.hotel.hotel_backend.entity.RoomUnitStatus;

import java.time.OffsetDateTime;

public record RoomUnitResponse(
        Long id,
        Long roomId,
        String roomNumber,
        Integer floor,
        RoomUnitStatus status,
        String notes,
        String coverImageUrl,
        boolean autoGenerated,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt
) {}
