package com.hotel.hotel_backend.service;

import com.hotel.hotel_backend.entity.Room;
import com.hotel.hotel_backend.entity.RoomUnit;
import com.hotel.hotel_backend.entity.RoomUnitStatus;
import com.hotel.hotel_backend.exception.ApiException;
import com.hotel.hotel_backend.exception.ErrorCode;
import com.hotel.hotel_backend.repository.RoomUnitRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Comparator;
import java.util.List;

@Service
@RequiredArgsConstructor
public class RoomUnitProvisionService {

    private final RoomUnitRepository roomUnitRepository;

    /**
     * Đồng bộ số lượng RoomUnit với Room.quantity.
     * Gọi sau khi tạo Room mới hoặc khi quantity thay đổi.
     * Chạy trong cùng transaction với caller — nếu fail thì rollback toàn bộ.
     */
    @Transactional
    public void syncUnitsWithQuantity(Room room) {
        long currentCount = roomUnitRepository.countByRoomId(room.getId());
        int target = room.getQuantity();

        if (currentCount < target) {
            generateMissingUnits(room, (int) (target - currentCount));
        } else if (currentCount > target) {
            removeExtraUnits(room, (int) (currentCount - target));
        }
    }

    @Transactional
    public void generateMissingUnits(Room room, int count) {
        for (int i = 0; i < count; i++) {
            RoomUnit unit = new RoomUnit();
            unit.setRoom(room);
            unit.setRoomNumber(null);
            unit.setFloor(null);
            unit.setStatus(RoomUnitStatus.AVAILABLE);
            unit.setNotes(null);
            unit.setAutoGenerated(true);
            roomUnitRepository.save(unit);
        }
    }

    @Transactional
    public void removeExtraUnits(Room room, int count) {
        List<RoomUnit> candidates = roomUnitRepository.findByRoomIdAndStatusInOrderByCreatedAtAsc(
                room.getId(), List.of(RoomUnitStatus.AVAILABLE, RoomUnitStatus.CLEANING));

        if (candidates.size() < count) {
            long blocked = roomUnitRepository.countByRoomId(room.getId()) - candidates.size();
            throw new ApiException(ErrorCode.VALIDATION_ERROR,
                    "Không thể giảm số lượng phòng: còn " + blocked +
                    " phòng đang sử dụng hoặc bảo trì. " +
                    "Hãy cập nhật trạng thái các phòng đó trước.");
        }

        // Ưu tiên xóa: (1) tự động sinh + chưa đặt số, (2) tự động sinh + có số, (3) đặt tay
        candidates.sort(Comparator
                .<RoomUnit, Integer>comparing(u -> {
                    if (u.isAutoGenerated() && u.getRoomNumber() == null) return 0;
                    if (u.isAutoGenerated()) return 1;
                    return 2;
                })
                .thenComparing(RoomUnit::getCreatedAt));

        candidates.subList(0, count).forEach(roomUnitRepository::delete);
    }
}
