package com.hotel.hotel_backend.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.OffsetDateTime;

@Getter
@Setter
@Entity
@Table(name = "room_units", uniqueConstraints = {
        @UniqueConstraint(name = "uq_room_unit_number", columnNames = {"room_id", "room_number"})
})
public class RoomUnit {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "room_id", nullable = false)
    private Room room;

    /** Số phòng do partner tự đặt, ví dụ: "101", "302A". Nullable khi mới tạo. */
    @Column(name = "room_number", length = 20)
    private String roomNumber;

    private Integer floor;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private RoomUnitStatus status = RoomUnitStatus.AVAILABLE;

    @Column(length = 500)
    private String notes;

    @Column(name = "guest_name", length = 200)
    private String guestName;

    @Column(name = "cover_image_url", length = 1000)
    private String coverImageUrl;

    @Column(name = "auto_generated", nullable = false)
    private boolean autoGenerated = false;

    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;

    @PrePersist
    void prePersist() {
        OffsetDateTime now = OffsetDateTime.now();
        createdAt = now;
        updatedAt = now;
    }

    @PreUpdate
    void preUpdate() {
        updatedAt = OffsetDateTime.now();
    }
}
